name: deploy-infra-azure

on: 
  push:
    branches:
      - main
    tags:
      - v1.** # Trigger on tags that start with v1.
    paths:
        - 'deplpy/**' # Trigger on changes to the src directory.

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - actions/checkout@v3
      - run: az bicep build --file ./deploy/main.bicep
        name: Run Bicep linter
